Airbnb:
  outputs:
    dev:
      account: OZGEEKK-KZ17734
      database: AIRBNB
      password: MinerCanada@9192
      role: ACCOUNTADMIN
      schema: DEV
      threads: 1
      type: snowflake
      user: akshit
      warehouse: BIKESHARING_WH
  target: dev
dbtlearn:
  outputs:
    dev:
      account: null
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
